# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-io-nbdev',
                'doc_host': 'https://Binjian.github.io',
                'git_url': 'https://github.com/Binjian/data-io-nbdev',
                'lib_path': 'data_io_nbdev'},
  'syms': {'data_io_nbdev.core': {'data_io_nbdev.core.say_hello': ('core.html#say_hello', 'data_io_nbdev/core.py')}}}
