# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_sandbox.ipynb.

# %% auto 0
__all__ = ['say_hello', 'HelloSayer']

# %% ../nbs/99_sandbox.ipynb 4
def say_hello(to: str):
    """Say hello to somebody"""
    return f'Hello {to}!'

# %% ../nbs/99_sandbox.ipynb 16
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to
    def say(self): return say_hello(self.to)
