project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "tspace"
  site-url: "https://Binjian.github.io/tspace"
  description: "io interface"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/Binjian/tspace"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/Binjian/tspace"
  sidebar:
    style: "floating"

metadata-files:
  - sidebar.yml
  - custom.yml
