name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install IDQL 
        run: pip install git+https://github.com/Binjian/IDQL.git  

      - name: Quarto
        uses: Binjian/workflows/quarto-ghp@master
