name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install IDQL 
        run: pip install git+https://github.com/Binjian/IDQL.git  

      - name: Quarto
        uses: Binjian/workflows/nbdev-ci@master
